spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/e-commerce;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;AUTO_SERVER=TRUE
    username: sa
    password: 

token:
  expiration_time: 86400000
  secret: '{cipher}AQBorYtRlrjTYi+Q+YdoDhQcknRmMYBVewMm3LOEqkvBzwUpqYRAJWdClcwvTo3iFsxljUzhBOShh3GO96xtfKhh1ZpTJHenebOk1ezNrrctGOlXiVup4Tgk5HELu5n1wYF+gQ/KtgWCqyrBJNtUVUeeMGka7JvC/Pgc1wTKGQxZcjLyz/LfTfchpPsnLI0L9J3WrR7lmKhY7oyYORdxbxAbsmB+eVWV0dhaFQ391NPqYMni97BKkZ+1HYUcz9HjqCWvZG2q0k+ha3bfS/9onybKvGJr45XkHlVY+q8Ej8X3Fu3YAoR0h8y+Yu5k+zx9QoUsrm8pKzJ1BpcskL7bl+O+UbGh7DpCfbn/BKmkW8Vw+TVetw54wO6qjOc59uTmSVMaqEQGP0LB4KQyc9t2j1GC'

gateway:
  ip: 192.168.4.4

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
