spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/e-commerce
    username: sa
    password:

token:
  expiration_time: 86400000
  secret: my_token_default

gateway:
  ip: 192.168.4.3